apiVersion: operator.serverless.openshift.io/v1alpha1
kind: KnativeKafka
metadata:
  name: knative-kafka
  namespace: knative-eventing
spec:
  broker:
    defaultConfig:
      numPartitions: 10
      replicationFactor: 3
      bootstrapServers: 'kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092'
    enabled: true
  channel:
    enabled: true
    bootstrapServers: 'kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092'
  logging:
    level: DEBUG
  sink:
    enabled: true
  source:
    enabled: true