apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wealthwise-transact
  namespace: wealthwise
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: quay.io/rh-ee-dwaters/func-transact
          env:
            - name: KAFKA_BROKER
              value: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092