apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wealthwise-check-notifications
  namespace: wealthwise
spec:
  template:
    spec:
      containers:
        - image: quay.io/rh-ee-dwaters/func-check-notifications
          env:
            - name: KAFKA_BROKER
              value: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092
            - name: PGUSER
              value: pguser
            - name: PGPASSWORD
              value: abc123
            - name: PGHOST
              value: postgresql
            - name: PGDATABASE
              value: wealthwise
            - name: PGPORT
              value: "5432"