apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wealthwise-product-suggest
  namespace: wealthwise
spec:
  template:
    spec:
      containers:
        - image: quay.io/rh-ee-dwaters/func-product-suggest
          env:
            - name: KAFKA_BROKER_URL
              value: kafka-cluster-kafka-bootstrap.kafka.svc.cluster.local:9092